#ifndef MOVE_TSAK_ASSIGNMENT_GLOBAL_H
#define MOVE_TSAK_ASSIGNMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOVE_TSAK_ASSIGNMENT_LIBRARY)
#  define MOVE_TSAK_ASSIGNMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOVE_TSAK_ASSIGNMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOVE_TSAK_ASSIGNMENT_GLOBAL_H
