#ifndef TASKDISPOSE_GLOBAL_H
#define TASKDISPOSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TASKDISPOSE_LIBRARY)
#  define TASKDISPOSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TASKDISPOSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TASKDISPOSE_GLOBAL_H
